# ============================================================
# MikroTik -> Graylog Production Logging
# SAFE / RERUNNABLE BASELINE
#
# CHANGE THIS BEFORE RUNNING:
:local graylogIP "YOUR_GRAYLOG_IP"
#
# Does NOT modify:
# - Firewall filter policy
# - NAT
# - Routes
# - IPsec configuration
# ============================================================

# ------------------------------------------------------------
# Graylog Remote Action
# ------------------------------------------------------------

:if ([:len [/system logging action find where name="graylog"]] = 0) do={
    /system logging action add \
        name=graylog \
        target=remote \
        remote=$graylogIP \
        remote-port=514 \
        remote-protocol=udp
} else={
    /system logging action set \
        [find where name="graylog"] \
        target=remote \
        remote=$graylogIP \
        remote-port=514 \
        remote-protocol=udp
}

# ------------------------------------------------------------
# Firewall
# Only forwards logs already generated by log=yes rules.
# ------------------------------------------------------------

:if ([:len [/system logging find where topics="firewall" action="graylog"]] = 0) do={
    /system logging add topics=firewall action=graylog
}

# ------------------------------------------------------------
# Login / Logout
# ------------------------------------------------------------

:if ([:len [/system logging find where prefix="ACCOUNT: "]] = 0) do={
    /system logging add \
        topics=account \
        action=graylog \
        prefix="ACCOUNT: "
}

# ------------------------------------------------------------
# Configuration Changes
# ------------------------------------------------------------

:if ([:len [/system logging find where prefix="CONFIG: "]] = 0) do={
    /system logging add \
        topics=system \
        action=graylog \
        prefix="CONFIG: " \
        regex="changed by"
}

# ------------------------------------------------------------
# Warning
# ------------------------------------------------------------

:if ([:len [/system logging find where prefix="WARNING: "]] = 0) do={
    /system logging add \
        topics=warning \
        action=graylog \
        prefix="WARNING: "
}

# ------------------------------------------------------------
# Error
# ------------------------------------------------------------

:if ([:len [/system logging find where prefix="ERROR: "]] = 0) do={
    /system logging add \
        topics=error \
        action=graylog \
        prefix="ERROR: "
}

# ------------------------------------------------------------
# Critical
# ------------------------------------------------------------

:if ([:len [/system logging find where prefix="CRITICAL: "]] = 0) do={
    /system logging add \
        topics=critical \
        action=graylog \
        prefix="CRITICAL: "
}

# ------------------------------------------------------------
# IPsec
# ------------------------------------------------------------

:if ([:len [/system logging find where prefix="IPSEC: "]] = 0) do={
    /system logging add \
        topics=ipsec,!debug,!packet \
        action=graylog \
        prefix="IPSEC: "
}

:put "=========================================="
:put "Graylog logging configuration complete"
:put "=========================================="
:put ("Graylog server: " . $graylogIP . ":514/UDP")
:put ""
:put "Check with:"
:put "/system logging action print detail"
:put "/system logging print detail"
